package.json
ui/components/Queue.js
ui/index.css
ui/index.js
ui/xcode.css
webpack.config.js
yarn.lock

the new lib is based on highlight.js, which gives highlights for more languages
thus we can prettify the error stacktrace too 🎉
also makes snyk happy since this one doesn't contain vulnerability issues 🤷‍♀️
closes #6

highlight: replace libs with more powerful one

---

README.md
index.js

Per the spec https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queue creating a Queue can support additional options. This adds support for that.

Support for creating a Queue with options

---

.gitignore
index.js
routes/cleanAll.js
ui/components/App.js
ui/components/Queue.js
ui/components/hooks/useStore.js

There is now a button in the Delayed tab that cleans jobs.
It's difficult for me to test that this actually works.  Here's what I've been doing to test that this works:
1) Put the same Clean All button into failed jobs
2) Click it and verify that it moves the failed jobs into Waiting
This works.
Is there a simple way to create a test job that is Delayed, so I can test this more directly?
I've tried calling [moveToDelayed()](https://github.com/OptimalBits/bull/blob/develop/lib/job.js#L300) on newly created jobs, but that seems to move the jobs to Waiting rather than Delayed, so I can't test the Clean All button.  Or, perhaps it moves the jobs to the delayed status for a brief second, but they are immediately promoted to the waiting status for processing.  Either way, I can't test the Clean …

Add 'Clean Jobs' to Delayed Jobs

---

ui/xcode.css

fixes #16 
breaks lines as expected:

code-highligthing: add pre-wrap property to break lines

---

ui/components/Queue.js

jobs might have progress reports with values that are bigger than 100
this at least prevents the progress bar to break and instead show only the number
fixes #17

job-progress: fix percentage value when gt 100

---

routes/index.js

We want to be able to configure a different path from the one
mounted on Express router.
For example, if we use a reverse proxy that rewrite our path we
want to be able to load the UI.

feat: use `proxyUrl` if provided

---

ui/components/Queue.js

I've added a time format for delayed jobs. so it'll show a more human-readable time format instead of the remaining millisecond. for example, it shows `about 1 hour` instead of `3600000`.
a little technical choice here is that I used `formatDistance` instead of `formatDistanceToNow` as it was already imported in the `Queue.js` file. we can also use `formatDistanceStrict` which would give more exact timing (for example `43 minutes`). which one do you think users would be happier with?

feat: distance time for delayed jobs

---

README.md
example.js
index.js
package.json
routes/cleanAll.js
routes/getDataForQeues.js
routes/queues.js
ui/components/Queue.js
yarn.lock

Hi,
I added support for bull v4 (#38). 
- Now, bull and bullmq are both optional peer dependencies and must be added by the user.
- The bull version is displayed on the dashboard
- For now, the `createQueues` function does not support bull 4
Unrelated (I can move it to another PR if you want), I added a button to toggle data instead of displaying it directly. In case of big data blob, the UI was freezing
closes #32 
closes #38

Add support for bullmq (bull v4) and some small improvements 

---

package.json
yarn.lock

These types are needed in the production bundle, so I've moved them from dev deps to proper reps.
Closes #85

Move type dependencies from dev to production

---

src/ui/components/hooks/useStore.ts

When you have "/" characters in queue names like:
@domain/queueName
Then UI will prepare requests like:
http://localhost:3000/ui/queues/@func/queueName/clean/failed
and server will resolve this as "404".
This fix uses urlEncode on queuName before we send request.
http://localhost:3000/ui/queues/%40func%2FqueueName/clean/failed
and server resolve with "200" status.
PS. I was use **encodeURIComponent()** instead of **qs.encode()** couse of compiling problems - need webpack reconfigurations.

Wrap encodeURIComponent to queueName in store methods

---

.gitignore
src/index.spec.ts
src/index.ts

This target to sync 1:1 queues that are available in-app and in bull-board.
The pseudocode here is
```ts
const queues = [];
setQueues(queues);
app.use("/", UI);
app.post("/queues", (req, res) => {
queues.push(new Queue(...req.body));
setQueues(queues); // this one is ok, we're adding a queue
});
app.delete("/queues/:id", () => {
queues.splice(req.params.id, 1);
// setQueues(queues); // this one will not work, because it doesn't perform a removal
replaceQueues(queues);
});
```

feat: allow to replace queues completely

---

package.json

Webpack is currently outputting the types to dist/index.d.ts, but isn't being referenced by package.json. This causes vscode to recommend to me to install @types/bull-board, which contains incorrect typings for the project.

Add type locations in package.json

---

package.json
routes/getDataForQeues.js
yarn.lock

Hey @vcapretz! I've fixed displaying of cached redis stats in version 0.6.0. Could you create a branch for fixes for previous release, so that I can change base branch for my PR?

Fixed redis stats block

---

src/ui/components/Queue.tsx

In terms of UI, having several queues listed one after each other, it seemed nicer to be able to close them on click, without having to click on a different queue.
See below for the implemented behaviour:

Close job tab on click

---

src/ui/components/Job.tsx

Having sometimes very long ids for our jobs, it messes up with the UI and shifts all the content to the right side.
A workaround we found is having the possibility to toggle the `id` data when it's too long, the same way you can toggle `json` data for jobs.

Toggle id display for job

---

src/index.ts
src/routes/cleanJob.ts
src/ui/components/App.tsx
src/ui/components/Job.tsx
src/ui/components/Jobs.tsx
src/ui/components/Queue.tsx
src/ui/components/constants.ts
src/ui/components/hooks/useStore.ts

Thanks again for this very useful library 🙂 
While using it, my team and I realised that having a functionality where you could individually delete a job was missing.
So we've implemented in a fork of your library and decided to make a PR.
The idea is to have a CTA next to other job CTAs and be able to clean a specific job and not necessarily all of them at once.
Looking forward having your opinion on that, thanks for your time !

Add clean single job functionality

---

ui/index.ejs
ui/index.js

This is a minor change that moves the `basePath` from a write to `window.basePath` and into an attribute on the root element so that domains which use CSP to prevent inline scripts will be able to use bull-board.
This PR is to the latest-stable branch but I'd be happy to submit it to master and backport it to latest-stable.

improve support for domains which reject inline scripts

---

src/ui/index.ejs
src/ui/index.tsx

This pr passed the basePath to <base> tag, it removes the need for inline script.
fixes #91 & #130

Read base path from <base>, removes the inline scripts

---

src/ui/components/Highlight/Highlight.tsx
webpack.config.js

Make the build much faster by excluding `node_modules` from babel-loader

fix: "Cannot assign to read only property 'exports'" error

---

babel.config.js
package.json
src/ui/components/Header/Header.module.css
src/ui/components/Highlight/Highlight.tsx
src/ui/components/Menu/Menu.module.css
webpack.config.js
yarn.lock

This PR adds:
1. HMR for styles
2. React fast refresh for react components
3. Open dev env on `yarn build:ui:watch`
4. Adds error overlay
In order to enable it, 
1. Move to babel as TS transpiler (instead of ts-loader)
2. Enable webpack-dev-server to handle HMR (proxies `/ui` to the origin server)
**This PR relays on merge of** https://github.com/vcapretz/bull-board/pull/188

HMR for dev mode

---

.eslintrc.js
src/index.ts
src/queueAdapters/bull.ts
src/queueAdapters/bullMQ.ts
src/ui/components/Highlight/languages/stacktrace.ts
src/ui/hooks/useScrolled.ts

This PR fixes all lint warnings related to return type, disables it on `.tsx` file type

Handle better return type lint rule

---

routes/getDataForQeues.js

This fixes a case where bull returns `null` for a job. I am not sure why bull does that but this PR adds a null check to prevent the app from crashing
fixes #43

add null check when job is undefined

---

README.md
src/@types/app.ts
src/index.spec.ts
src/queueAdapters/bull.ts
src/queueAdapters/bullMQ.ts
src/routes/cleanAll.ts
src/routes/cleanJob.ts
src/routes/promoteJob.ts
src/routes/queues.ts
src/routes/retryAll.ts
src/routes/retryJob.ts
src/ui/components/JobCard/JobCard.tsx
src/ui/components/QueuePage/QueuePage.tsx

This PR adds a `readOnlyMode` per queue.
In this mode, all queue & jobs related actions are removed from the UI.

Add read only mode, closes #219

---

src/@types/app.ts
src/queueAdapters/base.ts
src/queueAdapters/bull.ts
src/queueAdapters/bullMQ.ts
src/routes/queues.ts

@Jivings, I've added this ability with a different approach.
```js
// server.js
const Queue = require('bull')
const QueueMQ = require('bullmq')
const { setQueues, BullMQAdapter, BullAdapter } = require('bull-board')
const someQueue = new Queue()
const someOtherQueue = new Queue()
const queueMQ = new QueueMQ()
const someQueueAdapter = new BullAdapter(someQueue);
someQueueAdapter.setFormatter('data', ({ secret, ...rest }) => ({ ...rest })); // this will apply data formatter
someQueueAdapter.setFormatter('returnValue', ({ token, ...rest }) => ({ ...rest })); // this will apply returnValue formatter
setQueues([
someQueueAdapter,
new BullAdapter(someOtherQueue),
new BullMQAdapter(queueMQ),
]);
```
closes #204

feat: allow to pass a data & returnValue formatters

---

README.md

According to this file:
https://github.com/felixmosh/bull-board/blob/master/bullMQAdapter.d.ts
The correct name should be `BullMQAdapter`  (with uppercase B).

Fix typo (bullMQAdapter to BullMQAdapter)

---

packages/api/src/handlers/queues.ts
packages/api/src/queueAdapters/base.ts
packages/api/typings/app.ts
packages/ui/src/components/JobCard/Details/Details.tsx
packages/ui/src/components/JobCard/JobCard.tsx
packages/ui/src/components/JobCard/Timeline/Timeline.tsx

fix: Show failed jobs as failed in "latest" tab

---

packages/api/src/handlers/pauseQueue.ts
packages/api/src/handlers/queues.ts
packages/api/src/handlers/resumeQueue.ts
packages/api/src/queueAdapters/base.ts
packages/api/src/queueAdapters/bull.ts
packages/api/src/queueAdapters/bullMQ.ts
packages/api/src/routes.ts
packages/api/tests/api/index.spec.ts
packages/api/typings/app.ts
packages/ui/package.json
packages/ui/src/components/App.tsx
packages/ui/src/components/ConfirmModal/ConfirmModal.module.css
packages/ui/src/components/Icons/EllipsisVertical.tsx
packages/ui/src/components/Icons/Pause.tsx
packages/ui/src/components/Icons/Play.tsx
packages/ui/src/components/JobCard/Button/Button.module.css
packages/ui/src/components/Menu/Menu.module.css
packages/ui/src/components/Menu/Menu.tsx
packages/ui/src/components/QueueDropdownActions/QueueDropdownActions.module.css
packages/ui/src/components/QueueDropdownActions/QueueDropdownActions.tsx
packages/ui/src/components/QueuePage/QueuePage.tsx
packages/ui/src/components/StatusMenu/StatusMenu.module.css
packages/ui/src/components/StatusMenu/StatusMenu.tsx
packages/ui/src/hooks/useStore.ts
packages/ui/src/services/Api.ts
packages/ui/typings/app.d.ts
yarn.lock

feat: add pause / resume on queue level

---

examples/with-express-auth/index.js

The express just uses serverAdapter.getRouter(), so I think this is uneeded

Remove unused return value from `createBullBoard()`

---

packages/api/src/handlers/queues.ts
packages/api/src/queueAdapters/base.ts
packages/api/typings/app.ts

feat: add job name formatter

---

packages/api/src/handlers/queues.ts
packages/ui/src/hooks/useActiveQueue.ts
packages/ui/src/hooks/useInterval.ts
packages/ui/src/hooks/useStore.ts
packages/ui/src/services/Api.ts

Improve performance

---

README.md
packages/api/src/handlers/queues.ts
packages/api/src/queueAdapters/base.ts
packages/api/tests/api/index.spec.ts
packages/api/typings/app.ts
packages/ui/src/components/JobCard/JobActions/JobActions.tsx
packages/ui/src/components/JobCard/JobCard.tsx
packages/ui/src/components/QueueActions/QueueActions.tsx
packages/ui/src/components/QueuePage/QueuePage.tsx

For some queues, I'd like to be able to clear jobs but never retry them. 
This PR adds a `allowRetries` option that defaults to `true` and is superseded by `readOnlyMode`.
**Example**
```ts
const boardQueues = [new BullMQAdapter(commsQueue, { allowRetries: false })];
createBullBoard({
serverAdapter: new ExpressAdapter(),
queues: boardQueues,
});
```
**Use Case**
I have a queue responsible for notifications that are only relevant for a short period of time and if they fail, should not be retried. The bull dashboard is available by many people inside my company and I don't want others to accidentally hit the retry button and cause confusion for our users. However, clearing jobs is an important feature to keep.
**readOnlyMode**
Setting the `readOnlyMode` option will supersede this option and …

Add canRetry options to queue

---

examples/with-fastify-auth/cookieAuth.js
examples/with-fastify-auth/index.js
examples/with-fastify/index.js
packages/fastify/package.json
packages/fastify/src/FastifyAdapter.ts
yarn.lock

Fastify 4 is generally available
Resolves #418 
FYI: Fastify 4 dropped support for Node 12 and added support for Node 18

chore: upgrade to fastify 4

---

example.ts
packages/api/src/index.ts
packages/api/typings/app.ts
packages/express/src/ExpressAdapter.ts
packages/fastify/src/FastifyAdapter.ts
packages/hapi/src/HapiAdapter.ts
packages/koa/src/KoaAdapter.ts
packages/ui/src/components/Header/Header.module.css
packages/ui/src/components/Header/Header.tsx
packages/ui/src/hooks/useUIConfig.ts
packages/ui/src/index.ejs
packages/ui/src/index.tsx
packages/ui/webpack.config.js

feat: Allow to change board title
feat: Allow to change board logo
closes #503

feat: Allow to pass uiConfig from server config to client

---

packages/api/src/handlers/queues.ts
packages/api/src/handlers/retryAll.ts
packages/api/src/handlers/retryJob.ts
packages/api/src/queueAdapters/base.ts
packages/api/src/queueAdapters/bull.ts
packages/api/src/routes.ts
packages/api/typings/app.ts
packages/ui/src/components/JobCard/JobActions/JobActions.tsx
packages/ui/src/components/JobCard/JobCard.tsx
packages/ui/src/components/QueueActions/QueueActions.tsx
packages/ui/src/components/QueuePage/QueuePage.tsx
packages/ui/src/hooks/useStore.ts
packages/ui/src/services/Api.ts
packages/ui/typings/app.d.ts

This PR adds support for retrying completed jobs when using the BullMQ adapter. Retrying completed jobs is not possible in bull, only in BullMq.
closes #506

feat: Allow retrying completed jobs when using BullMQ

---

packages/api/src/handlers/queues.ts

https://github.com/felixmosh/bull-board/blob/9c17cec31e296787fe0d8b53f0ae27806d6b2c0d/packages/api/src/handlers/queues.ts#L32
When the `jobProps.name` is undefined, the default value of `BaseAdapter.format(field, data, defaultValue = data)` will be `jobProps`. And then React will throw `Error: Minified React error #31;`.

fix: incorrect value of job name when job name is undefined

---

packages/api/src/handlers/queues.ts
packages/api/typings/app.ts

(via `changeDelay`), closes #544

fix: use job's delay attribute to reflect changes in delay 

---

packages/api/package.json

This closes https://github.com/felixmosh/bull-board/issues/564

Add @bull-board/ui as peerDep of @bull-board/api

---

README.md
examples/with-nestjs-module/.gitignore
examples/with-nestjs-module/README.md
examples/with-nestjs-module/docker-compose.yml
examples/with-nestjs-module/nest-cli.json
examples/with-nestjs-module/package.json
examples/with-nestjs-module/src/app.module.ts
examples/with-nestjs-module/src/feature/feature.controller.ts
examples/with-nestjs-module/src/feature/feature.module.ts
examples/with-nestjs-module/src/main.ts
examples/with-nestjs-module/tsconfig.build.json
examples/with-nestjs-module/tsconfig.json
packages/nestjs/README.md
packages/nestjs/package.json
packages/nestjs/src/bull-board.constants.ts
packages/nestjs/src/bull-board.decorator.ts
packages/nestjs/src/bull-board.feature-module.ts
packages/nestjs/src/bull-board.module.ts
packages/nestjs/src/bull-board.root-module.ts
packages/nestjs/src/bull-board.types.ts
packages/nestjs/src/bull-board.util.ts
packages/nestjs/src/index.ts
packages/nestjs/tsconfig.json
yarn.lock

As discussed in [#303,](https://github.com/felixmosh/bull-board/issues/303#issuecomment-1586974364)  I created a new package called `nestjs-bull-board` to easily integrate bull-board with NestJS. After some back and forth between @felixmosh and me, the library reached a state where it can be integrated into the `bull-board` mono-repo 😄 
- Added a new package to the mono-repo `@bull-board/nestjs`
- Added the existing package code from https://github.com/DennisSnijder/nestjs-bull-board to the new package.
- Updated documentation on the package README.md to match the new package name.

NestJS package

---

packages/ui/src/components/JobCard/Timeline/Timeline.tsx

**Current Behavior:**
For jobs that complete in under 5 seconds, the system currently displays the duration as "less than 5 seconds". This approach obscures the details for tasks that finish in mere milliseconds.
**Proposed Change:**
To provide more granular information about job execution times, this pull request introduces an enhanced time formatting mechanism:
Jobs that take less than 1 second will display their duration in milliseconds (e.g., "320 miliseconds").
Jobs that take between 1 to 5 seconds will display their duration with a precision of two decimal places (e.g., "3.25 seconds").
**Rationale:**
This change ensures that users have a clear understanding of the job durations, especially for those that complete rapidly. It will be particularly valuable for performance monitoring …

Enhanced Time Formatting for Short-duration Jobs

---

packages/express/src/ExpressAdapter.ts

Private fields make it difficult to extends ExpressAdapter. Using protected instead make ExpressAdapter open to extension.
Close #626

[express] Make ExpressAdapter fields protected instead of private

---

examples/with-express/index.js
examples/with-express/package.json
examples/with-express/yarn.lock

I just discovered this project (thanks for sharing it with the community btw!) and wanted to test it before migrating my current bull-arena, this example needed upgrade as BullMQ's QueueScheduler is not needed nowadays plus the very own express adapter and express.

upgrade-express-ex: upgrade versions + remove QueueScheduler

---

packages/api/typings/app.ts
packages/nestjs/src/bull-board.types.ts

Thanks for your awesome work!
Here is a typing PR to add the ability to modify one attribute only and not the whole option object.

Update QueueAdapterOptions typing

---

packages/ui/src/components/SettingsModal/SettingsModal.tsx
packages/ui/src/hooks/useDetailsTabs.tsx
packages/ui/src/hooks/useSettings.ts
packages/ui/src/static/locales/en-US/messages.json

Hi @felixmosh! First of all, thank you for this amazing tool! We use it everyday and really enjoy it. This is my first PR on this project, would love to get any feedback from you and hope it will be useful for other users as well 🙏
In our project, we were required to implement this feature https://github.com/felixmosh/bull-board/issues/264. So basically, we want to have "logs" tab to be opened by default. 
To make the solution more flexible I decided to create setting **default-job-tab** which is used for selecting initial job tab.
* Add pt-BR locales
This commit adds a new setting for the default job tab in the SettingsModal component. The selected default job tab is stored in the useSettingsStore and can be changed by the user.

Add default job tab setting

---

packages/ui/src/components/JobCard/Timeline/Timeline.tsx
packages/ui/src/static/locales/en-US/messages.json

looking a the issue i see you guys don't want to support getting the real run at time from the redis sorted sets score value instead  you want bullmq to add job.runAt field, can we at least have this ? 
added `*Delay changed; the new run time is currently unknown` under run at if the initial delay does not equal the current delay as Bullmq  does not return a timestamp for when the job will actually run, also i changed it to use the initial delay using the current delay will give you wrong run at time anyways.

feat: show message under run time if delay has changed

---

packages/nestjs/src/bull-board.root-module.ts

Fixes #607.
Apparently https://github.com/felixmosh/bull-board/pull/592 doesn't work with Fastify and https://github.com/felixmosh/bull-board/pull/639 adds Fastify support.
But both PRs fail loading the static folder correctly when global prefix doesn't start with a forward slash.
It was mentioned here https://github.com/felixmosh/bull-board/pull/592#issuecomment-1628526095 with https://github.com/felixmosh/bull-board/issues/607#issuecomment-1833471506 as the solution.
This PR does 2 things:
1. Makes sure that there is a leading forward slash in the `adapter.basePath` to correctly load the static folder for both Express and Fastify.
2. Fastify `prefix` option should be equal to the `adapter.basePath`.
I've setup 2 codesandboxes for you to verify this PR:
NestJS + Express: …

feat: [NestJS] Fastify global prefix support

---

packages/api/src/handlers/addJob.ts
packages/api/src/queueAdapters/base.ts
packages/api/src/queueAdapters/bull.ts
packages/api/src/queueAdapters/bullMQ.ts
packages/api/src/routes.ts
packages/api/typings/app.ts
packages/express/src/ExpressAdapter.ts
packages/fastify/src/FastifyAdapter.ts
packages/h3/src/H3Adapter.ts
packages/hapi/src/HapiAdapter.ts
packages/hono/src/HonoAdapter.ts
packages/koa/src/KoaAdapter.ts
packages/ui/package.json
packages/ui/src/components/AddJobModal/AddJobModal.tsx
packages/ui/src/components/Form/JsonField/JsonField.tsx
packages/ui/src/components/Icons/Add.tsx
packages/ui/src/components/QueueDropdownActions/QueueDropdownActions.tsx
packages/ui/src/hooks/useQueues.ts
packages/ui/src/services/Api.ts
packages/ui/src/static/locales/en-US/messages.json
packages/ui/typings/app.d.ts
packages/ui/typings/global.d.ts
yarn.lock

#426
- only test example.ts (Express). I'm not familiar with other adaptors
- jsoneditor's modal in modal need additional config, but I don't know how https://github.com/josdejong/jsoneditor/issues/895
- I only add enUS
- You may need replace Icon to match theme

Add Job Modal

---

packages/ui/src/components/JobCard/Progress/Progress.tsx

Here is an example showing 18.18181818%:
We don't need the decimals. Or we could keep one or two if you prefer.

Round Progress percent (JobCard)

---

packages/express/package.json

Per SYNK we should upgrade express to 4.19.2

Close express security vulnerability (4.19.2) 

---

packages/api/typings/app.ts
packages/ui/src/components/JobCard/Timeline/Timeline.tsx

#743
- New config `dateFormats` in `UIConfig`
- `short` : When timestamp is in same day (today)
- `common` : When timestamp is in same year
- `full`
Seem like `Timeline` is the only place that have date/time format, I didn't check other page/component

feat: custom job timeline date format

---

packages/ui/package.json
yarn.lock

#744 introduced `jsoneditor` and later you migrate to use `codemirror`.

chore: remove unused libs

---

packages/nestjs/src/bull-board.module.ts
packages/nestjs/src/bull-board.root-module.ts
packages/nestjs/src/bull-board.types.ts

This PR extends the [NestJS Dynamic Module](https://github.com/felixmosh/bull-board/blob/c208d35ae9f38f86c348a561407cee5050bb539d/packages/nestjs/src/bull-board.module.ts) by adding support for async configuration.
The async configuration allows us to inject/import modules or services we need to construct the module.
Example scenario of our usecase:
```ts
ConfigModule.forRoot({ envFilePath: './.env' }),
BullBoardModule.forRootAsync({
imports: [ConfigModule], // Import Nest configuration module
inject: [ConfigService], // Inject Nest configuration service
useFactory: (configService: ConfigService) => ({
route: configService.getOrThrow('QUEUE_PATH'), // Get path from Nest configuration service
adapter: ExpressAdapter,
})
}),
```

feat: Add Async Configuration Support to NestJS Module

---

packages/fastify/src/FastifyAdapter.ts

This hides the bullboard routes from openAPI schema generation. These routes don't have a schema defined, so they aren't useful in that context.

Hide bull routes from schema/openAPI generation

---

packages/nestjs/README.md

I've just installed bull board by following the README example, and somehow building the project was failing to me with following message:
```
src/main/worker.module.ts:19:31 - error TS2307: Cannot find module '@bull-board/api/bullMQadapter' or its corresponding type declarations.
19 import { BullMQAdapter } from '@bull-board/api/bullMQadapter';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
After a bit of inspecting I've found out that import path (that I've took from the README example) is incorrect.

fix(README): use proper path to bullMQAdapter file

---

packages/hono/src/HonoAdapter.ts

The web UI does not include a request body in most of its requests to the API. Hono's `c.req.json()` method throws if it cannot parse the body (at least on v4, I noticed bull-board is still on v3). This causes all of the mutations in the UI to fail, except for those that include a body such as adding a job.
This PR is a small change to safely attempt to parse the request body.

fix(hono): safely parse request body

---

packages/ui/src/components/JobCard/Progress/Progress.module.css
packages/ui/src/components/JobCard/Progress/Progress.tsx

Closes #771 
The `stroke-dasharray` and `stroke-dashoffset` were improperly calculated, resulting in the progress circle "completing" when the percentage was only 90%.
Current version:
I refactored the styling to make it more declarative. I also removed the rounded edge on the border so there is a gap with the percentage > 98%.
Fixed version:

fix(ui): correctly calculate the circumference and offset of the progress citcle

---

packages/hono/package.json
packages/hono/src/HonoAdapter.ts
yarn.lock

Support Hono V4. Since the adapters are not versioned separately, I tried to make a minimally-breaking change - it requires no changes unless you use Cloudflare Workers, which has a breaking change in Hono v4[^1]. 
This makes the types in the `HonoAdapter` slightly unsound. A proper long-term fix would be to change the API to accept `handler: ({ root, rewriteRequestPath }) => MiddlewareHandler` (where `MiddlewareHandler` is the return type of `serveStatic`).
Consumers could then construct `serveStatic` themselves, including requirements such as the manifest. That would, of course, require _every_ consumer to update their `HonoAdapter` constructor, so maybe something to reserve for a major release.
Closes #721 (supersedes)
[^1]: https://github.com/honojs/hono/blob/main/docs/MIGRATION.md#ser …

feat(adapters): support hono v4

---

examples/with-nestjs/src/queues/basic-auth.middleware.ts

I have elaborated on the basic auth example to be more production friendly, of course open for feedback.
Changes
- Replace hardcoded credentials with ConfigService-based configuration
- Implement bcrypt for secure password hashing and comparison
- Improve error handling and code structure
This change significantly improves the security of the Bull Board authentication

Enhance basic-auth.middleware example with password hashing and env variables

---

packages/ui/src/components/SettingsModal/SettingsModal.tsx

Based on feature request 789, disabled polling options other than "Off" if in "read only" mode in the Settings Modal.

marked polling-interval option to off and disabled other polling options if readonly mode is enabled

---

packages/ui/src/components/Header/Header.module.css

Hi! 
This is a minor tweak to the CSS for the header logo and image. It allows the image to be center-aligned vertically, and the image max height is set to the height of the container. This change allows users to set whatever height and width they want for the image, and it will auto-scale in the container.
Thanks!

Center align logo image in header

---

packages/fastify/package.json
yarn.lock

Last week Fastify v5 was released - https://github.com/fastify/fastify/releases
This PR addresses this issue https://github.com/felixmosh/bull-board/issues/823 and updates the relevant dependencies in order to support Fastify v5.
`@fastify/static` got support for v5 in version 8.0.1 and `@fastify/view` got support for it in version 10.0.1

Update Fastify dependencies to support Fastify v5

---

packages/ui/src/components/JobCard/JobCard.tsx
packages/ui/src/components/JobCard/Progress/Progress.tsx

I am using bull board with bullMQ, in the job progress I am sending an object e.g.: 
`{ progress: 70, total: 100, completed: 50 }`
when I set the job progress as an object the progress percentage is no longer displayed in bullboard.
I updated the component to show the progress whether it is a number or an object.
I think this change will be beneficial to many people who pass an object in the job progress.

Show percentage when progress is an object

---

packages/ui/package.json
packages/ui/src/App.tsx
packages/ui/src/components/Button/Button.module.css
packages/ui/src/components/Card/Card.module.css
packages/ui/src/components/Header/Header.module.css
packages/ui/src/components/JobCard/Details/Details.module.css
packages/ui/src/components/JobCard/Details/DetailsContent/JobLogs/JobLogs.module.css
packages/ui/src/components/JobCard/JobCard.module.css
packages/ui/src/components/Modal/Modal.module.css
packages/ui/src/components/QueueCard/QueueStats/QueueStats.module.css
packages/ui/src/components/SettingsModal/SettingsModal.tsx
packages/ui/src/components/StatusLegend/StatusLegend.module.css
packages/ui/src/components/StatusMenu/StatusMenu.module.css
packages/ui/src/components/StickyHeader/StickyHeader.module.css
packages/ui/src/index.css
packages/ui/src/static/locales/en-US/messages.json
packages/ui/src/static/locales/es-ES/messages.json
packages/ui/src/static/locales/fr-FR/messages.json
packages/ui/src/static/locales/pt-BR/messages.json
packages/ui/src/static/locales/zh-CN/messages.json
yarn.lock

#471
Dark mode is added using [next-themes](https://github.com/pacocoursey/next-themes), a switch is added in the configuration to be able to change between light and dark, the default mode is the system mode.

Dark mode 🌙

---

packages/ui/src/components/StatusLegend/StatusLegend.module.css
packages/ui/src/components/StatusLegend/StatusLegend.tsx
packages/ui/src/hooks/useSelectedStatuses.ts
packages/ui/src/pages/OverviewPage/OverviewPage.tsx

Following the discussion on https://github.com/felixmosh/bull-board/pull/742, I added some simple links to the `StatusLegend` so it's now possible to filter queues based on a given status. This can be useful to direct link to a list of failed queues from some alerting system for example:
I've tried to reuse as much as I could from existing components but I'm unsure whether you tend to duplicate similar things or not to future-proof them (for example I've reused css vars from `status-menu` in the StatusLegend module css but maybe that's an anti-pattern for you?).
Also, a current known limitation to this is that there is no `ALL` link (but we can click on the logo for example to go back to the initial state) as I wasn't sure on how best to handle this (I'm a first-time contributor to this …

feat: add status filters on overview page

---

packages/ui/src/components/JobCard/JobActions/JobActions.tsx

As a happy user of bull-board when browsing the paused queue I noticed there was no action for deleting a job in a paused queue.
This PR adds the possibility to edit/duplicate and clean paused jobs.
I could not think of any reason why it's a bad idea not to expose these actions for paused jobs - did I miss something?

feat: paused jobs: support edit/duplicate/clean

---

packages/h3/src/H3Adapter.ts

If the queue or job was encoded (e.g. because it had a `/`) it could not be found because h3 does not decode the route param by default.

Fix h3 adapter route param decode

---

packages/ui/src/components/JobCard/JobActions/JobActions.tsx

Currently there's no possibility to delete a job which is in "waiting children" status. Yet, such a job can be awaiting another job which is simply in "waiting" status, which can be removed... and if you do that, you'll end up with a "zombie" job in "waiting children", that will never succeed, nor can be removed through the Bull Board.
Screenshot of the current behaviour:
This PR fixes it, making actions appear in a "waiting children" job just as in a "waiting" one.
Fixed behaviour:

fix(JobActions): show actions for "waiting children" jobs just as for "waiting" ones

---

packages/nestjs/package.json

Fixes the following issue in `BullBoardModule.forFeature`:
```
Type 'DynamicModule' is not assignable to type 'Type<any> | DynamicModule | Promise<DynamicModule> | ForwardReference<any>'.
Type 'import("/Users/snigdhasingh/Development/btp/node_modules/@mikro-orm/nestjs/node_modules/@nestjs/common/interfaces/modules/dynamic-module.interface").DynamicModule' is not assignable to type 'import("/Users/snigdhasingh/Development/btp/node_modules/@nestjs/common/interfaces/modules/dynamic-module.interface").DynamicModule'.
Types of property 'imports' are incompatible.
Type '(DynamicModule | Type<any> | Promise<DynamicModule> | ForwardReference<any>)[] | undefined' is not assignable to type '(Type<any> | DynamicModule | Promise<DynamicModule> | ForwardReference<any>)[] | undefined'.
Type …
```

fix: allow nestjs v11

---

packages/api/src/handlers/queues.ts

Closes #862 
A user reported that when they retry failed jobs they want to be able to see the latest error at the top and this PR fixes this problem so that users don't need to scroll down to find the last error for a failed job.
 
The only change made is in the `api` and that is reversing the order of the `stacktrace` array.

fix: reverse array to display recent errors

---

packages/elysia/src/ElysiaAdapter.ts

Recurring jobs were causing a 404 error when individually promoted or cancelled or retried etc.

Now able to interact with specific jobs with id's containing special chars

---

examples/with-elysia/index.ts

Although this is a minor change, I believe it's worth making. 
Changes:
Updated the import path for `ElysiaAdapter` to use a direct package reference instead of a relative path to **node_modules**. This ensures proper module resolution and improves code clarity.

Fix Elysia example

---

examples/with-elysia/index.ts
examples/with-elysia/package.json
packages/api/typings/app.ts

issue: https://github.com/felixmosh/bull-board/issues/913
Improve Elysia example by resolving Bun build issue caused by eval.
Changelog:
1. Fixed the @bull-board/elysia package version because the specified one didn't exist, causing Bun to fail when loading it.
2. Added the options.uiBasePath parameter to fix the build issue.
3. Added build and start commands to package.json—build compiles the project, and start runs the compiled version.
4. Updated the BoardOptions type to make uiConfig optional since it wasn’t actually required.

Improve Elysia example by resolving Bun build issue caused by eval.

---

example.ts
packages/api/src/handlers/queues.ts
packages/api/src/queueAdapters/base.ts
packages/api/typings/app.ts
packages/ui/src/components/Menu/MenuTree/MenuTree.tsx
packages/ui/src/components/QueueCard/QueueCard.tsx
packages/ui/src/components/Title/Title.tsx

Implements #921 
The nameAlias is optional. If provided, everywhere the queue name is currently rendered it will preference the `nameAlias` else fall back to the `name`

feat: Queue name alias

---

packages/hono/package.json
yarn.lock

If Hono is marked as a dependency, you are restricting users to only use the exact version specified in this repo. Using a peer dependency means type errors like [this](https://github.com/jonahsnider/frc-colors.com/actions/runs/15290145837/job/43007965325?pr=181#step:7:24) won't happen anymore.

fix(hono): make hono a peer dependency

---

packages/ui/src/constants/languages.ts
packages/ui/src/services/i18n.ts
packages/ui/src/static/locales/ja-JP/messages.json

Hello! I really appreciate this excellent dashboard tool.
As a native Japanese speaker, I'd love to contribute by adding Japanese localization. Please feel free to close this PR if Japanese support isn't needed 🙏
- Added ja-JP to supported languages
- Added Japanese date-fns locale mapping
- Added comprehensive Japanese translation

feat(ui): Add Japanese language

---

packages/ui/localesSync.config.js
packages/ui/src/constants/languages.ts
packages/ui/src/static/locales/en-GB/messages.json

- Add en-GB locale with proper British English translations
- Change 'Up time' to 'Uptime' (correct British spelling)
- Change 'memory stats' to 'memory statistics' (more formal British English)
- Enables 24-hour clock format in UI without requiring date-fns config changes

feat: add British English locale support

---

packages/api/package.json

import { BullMQAdapter } from "@bull-board/api/bullMQAdapter";

Allow importing "@bull-board/api/*Adapter" in ESM

---

packages/api/src/handlers/cleanJob.ts

It's related with #908.
It doesn't help to clean with `Clean all` Button.
But it will allow to delete specific jobScheduler job

support clean each jobScheduler job
