- dockest.js
- jest.config.js
- package.json
- routes/queues.spec.js
- yarn.lock
Introducing the libraries for trivial testing
The test file is more or less a placeholder to get things going
> Introduce dockest & jest

- README.md
- example.js
- index.js
Add ability to add already defined queues (using Bull)
> Add "add and setter" functions

- README.md
Moving the UI image to the top of README file for added visibility
> README: moving screenshot for more visibility

- .github/workflows/nodejs.yml
feat: pipeline timeouts
feat: pipeline website deployment
feat: pipeline npm publish
> Enhance pipeline 💪🏼

- .github/workflows/nodejs.yml
> run pipeline on PRs

- src/ui/components/Queue.tsx
> Fix wrong variable type at delayed page

- .gitignore
- package.json
- src/dockest.ts
- src/index.spec.ts
- tsconfig.json
- tsconfig.publish.json
- yarn.lock
Introduces dockest as a means to perform integration testing.
Supertest will be used to send and validate requests and responses.
closes #2
> Introduce integration testing

- package.json
- src/index.ts
fix bug with new alpha version
> import paths from correct place

- src/ui/components/constants.ts
> add opts and data to the list of fields in the failed tab

- package.json
- routes/getDataForQeues.js
- routes/pagination.js
- ui/components/App.js
- ui/components/Paginator.js
- ui/components/Queue.js
- ui/components/hooks/useStore.js
- ui/index.css
Implements #37 
- Prev / Next buttons for navigating pages
- Jump to page by number input, easier to inspect later on jobs when job list is large. (press enter to take effect - perhaps not so intuitive, but comparing to taking effect on every typing changes, this approach would save unnecessary request on redis. But any feedback are welcome)
- User input validation & error prevention
- Pagination boundary checks
This PR is based on the javascript version (`0.6.0`) to avoid wait on the latest TypeScript rewrite ([see discussion](https://github.com/vcapretz/bull-board/issues/37#issuecomment-633896558)), therefore this PR can only be merged to version `0.6.0` and not the latest alpha version. But once the project moves forward probably will need to refactor this ticket into TypeScript as …
> Add Pagination for Jobs List

- package.json
Alpha 11 with redesign of the ui
> Bump alpha version

- src/ui/components/JobCard/Details/Details.module.css
- src/ui/components/JobCard/Details/Details.tsx
- src/ui/components/JobCard/JobCard.module.css
> fix: long tab content overflows

- example.js
- src/@types/app.ts
- src/routes/queues.ts
- src/ui/components/Highlight/Highlight.tsx
- src/ui/hooks/useDetailsTabs.tsx
This feature adds the job's return value in the `Data` tab
If no return data
This PR relays on merge of #188
> Add return value 184

- README.md
Added documentation how to configure basePath in the Readme.md
> Close #217 Configure basePath doc

- src/ui/components/App.tsx
> fix: Handle an empty queue array

- src/@types/app.ts
- src/routes/queues.ts
- src/ui/hooks/useDetailsTabs.tsx
> Handle empty stacktraces, it comes as [null] / [""]

- src/routes/queues.ts
This PR filters out nullish jobs
> fix: Ignore nullish jobs, closes #176

- example.js
- src/@types/app.ts
- src/index.ts
- src/queueAdapters/base.ts
- src/queueAdapters/bull.ts
- src/queueAdapters/bullMQ.ts
- src/routes/jobLogs.ts
- src/ui/components/JobCard/Details/Details.module.css
- src/ui/components/JobCard/Details/Details.tsx
- src/ui/components/JobCard/Details/DetailsContent/DetailsContent.tsx
- src/ui/components/JobCard/Details/DetailsContent/JobLogs/JobLogs.module.css
- src/ui/components/JobCard/Details/DetailsContent/JobLogs/JobLogs.tsx
- src/ui/components/JobCard/JobCard.tsx
- src/ui/components/QueuePage/QueuePage.tsx
- src/ui/hooks/useDetailsTabs.tsx
- src/ui/hooks/useStore.ts
- src/ui/services/Api.ts
> Add job logs

- src/ui/components/JobCard/Details/DetailsContent/JobLogs/JobLogs.module.css
This PR adds the ability to show a multi line logs,
Closes #254
> feat: Allow line break in job logs

- packages/api/typings/app.d.ts
> fix: point global common typings to use dist

- packages/api/src/index.ts
> fix: Allow bull-board to be bundled with webpack

- packages/ui/package.json
- yarn.lock
due to https://github.com/radix-ui/primitives/issues/837
fixes #320
> Rollback @radix-ui/react-dropdown-menu 

- packages/ui/src/components/JobCard/JobCard.tsx
> fix: show retry button on failed tab (job can be retried)

- packages/api/src/queueAdapters/base.ts
- packages/api/src/queueAdapters/bull.ts
- packages/api/src/queueAdapters/bullMQ.ts
- packages/api/typings/app.ts
on different envs (prod, stage)
closes #331
> feat: Add prefix option to allow multiple queues with the same name

- packages/api/src/handlers/queues.ts
- packages/ui/src/hooks/useActiveQueue.ts
> fix: decode queue name to support url special chars

- packages/api/src/queueAdapters/bull.ts
- packages/ui/src/components/JobCard/JobCard.tsx
> fix: align attemptsMade to the behavior of BullMQ.

- packages/api/src/queueAdapters/bull.ts
> fix: check if the job exists

- examples/with-fastify-auth/basicAuth.js
- examples/with-fastify-auth/cookieAuth.js
- examples/with-fastify-auth/index.js
- examples/with-fastify-auth/package.json
- examples/with-fastify-auth/yarn.lock
- examples/with-fastify/package.json
- examples/with-fastify/yarn.lock
- packages/fastify/package.json
- packages/fastify/src/FastifyAdapter.ts
- yarn.lock
> Upgrade to @fastify/static package

- packages/api/src/handlers/queues.ts
- packages/api/src/queueAdapters/base.ts
- packages/api/typings/app.ts
- packages/ui/src/components/App.tsx
- packages/ui/src/components/Header/Header.module.css
- packages/ui/src/components/Header/Header.tsx
- packages/ui/src/components/QueueTitle/QueueTitle.module.css
- packages/ui/src/components/QueueTitle/QueueTitle.tsx
- packages/ui/src/components/RedisStats/RedisStats.module.css
- packages/ui/src/hooks/useActiveQueue.ts
- packages/ui/src/hooks/useStore.ts
> feat: add queue description option and show the queue name on the board.

- packages/koa/src/KoaAdapter.ts
> Allow to customize mount point

- packages/ui/src/components/JobCard/Details/Details.module.css
hi there👋
This PR adds vertical scrolling but hides the generated scrollbar.
https://user-images.githubusercontent.com/79164595/197317556-f85d3829-b65e-499b-bc74-d44ef0ff122e.mp4
> fix: add missing scrolling behavior

- packages/ui/src/components/Menu/Menu.module.css
> fix: search input style are affected by global input styles

- packages/api/src/handlers/emptyQueue.ts
- packages/api/src/queueAdapters/base.ts
- packages/api/src/queueAdapters/bull.ts
- packages/api/src/queueAdapters/bullMQ.ts
- packages/api/src/routes.ts
- packages/ui/src/components/QueueDropdownActions/QueueDropdownActions.tsx
- packages/ui/src/hooks/useStore.ts
- packages/ui/src/services/Api.ts
- packages/ui/typings/app.d.ts
> Add "empty queue" action

- README.md
- example.ts
- examples/with-express-auth/index.js
- examples/with-express/index.js
- examples/with-fastify-auth/basicAuth.js
- examples/with-fastify-auth/cookieAuth.js
- examples/with-fastify/index.js
- examples/with-hapi-auth/index.js
- examples/with-hapi/index.js
- examples/with-koa/index.js
- packages/express/src/index.ts
- packages/fastify/src/index.ts
- packages/hapi/src/index.ts
- packages/koa/src/index.ts
> Reexport api functions in server adapters

- examples/with-nestjs/.eslintrc.js
- examples/with-nestjs/.gitignore
- examples/with-nestjs/.prettierrc
- examples/with-nestjs/README.md
- examples/with-nestjs/nest-cli.json
- examples/with-nestjs/package-lock.json
- examples/with-nestjs/package.json
- examples/with-nestjs/src/app.controller.ts
- examples/with-nestjs/src/app.module.ts
- examples/with-nestjs/src/app.service.ts
- examples/with-nestjs/src/main.ts
- examples/with-nestjs/src/queues/basic-auth.middleware.ts
- examples/with-nestjs/src/queues/queues.module.ts
- examples/with-nestjs/src/queues/test.processor.ts
- examples/with-nestjs/tsconfig.build.json
- examples/with-nestjs/tsconfig.json
> Adds example with NestJS

- README.md
- packages/api/src/handlers/entryPoint.ts
- packages/api/src/index.ts
- packages/api/typings/app.ts
- packages/ui/src/index.ejs
- packages/ui/webpack.config.js
Allows changing the favicons.
Follows discussion in #584 
If you are ok with the solution I can make another PR updating the README with the new functionality.
> feat: Allow changing favicon paths

- packages/ui/src/App.tsx
- packages/ui/src/components/Menu/Menu.tsx
- packages/ui/src/components/Title/Title.tsx
- packages/ui/src/hooks/useActiveQueue.ts
- packages/ui/src/pages/JobPage/JobPage.tsx
- packages/ui/src/pages/QueuePage/QueuePage.tsx
@felixmosh just the hook improvement and prop reducing in this PR as agreed 👍🏽
> improved `useActiveQueue` to reduce prop depencency

- packages/express/package.json
- packages/fastify/package.json
- packages/h3/package.json
- packages/hapi/package.json
- packages/hono/package.json
- packages/koa/package.json
> bump ejs dependency in package.json

- packages/ui/src/utils/links.ts
> fix: encode queue name in links

- packages/ui/src/components/SettingsModal/SettingsModal.tsx
- packages/ui/src/static/locales/fr-FR/messages.json
Thanks for this great tool!
French is my mother tongue, so I can help with translation. If there is no need for this language, you can close this PR :wink:
> feat(ui): Add French language

- packages/ui/src/components/Menu/Menu.module.css
- packages/ui/src/components/Menu/Menu.tsx
Convenient manual check for updates
> feat(Menu): add version link to GitHub release page

- packages/ui/src/components/SettingsModal/SettingsModal.tsx
https://github.com/felixmosh/bull-board/issues/702
> adjust max jobs per page

- packages/ui/localesSync.config.js
- packages/ui/src/components/SettingsModal/SettingsModal.tsx
- packages/ui/src/static/locales/es-ES/messages.json
Added option to display texts in spanish language
> Spanish language added

- packages/ui/src/static/locales/es-ES/messages.json
- packages/ui/src/static/locales/fr-FR/messages.json
missing translations in French and Spanish
> missing translations

- packages/nestjs/README.md
This PR updates the documentation to include authentication setup for Bull-Board in NestJS using both Express and Fastify. The key additions are:
- Express Authentication: Instructions for securing Bull-Board with express-basic-auth.
- Fastify Authentication: Instructions for applying fastify-basic-auth as middleware.
- Clarification on Middleware Usage: Ensured that Fastify authentication is handled via middleware without modifying the adapter directly.
These updates aim to provide clear guidance on securing the Bull-Board UI in NestJS applications. No functional changes were made—this is purely a documentation enhancement.
> Document authentication setup for Express and Fastify in NestJS

- packages/elysia/src/ElysiaAdapter.ts
Apparently there are issues with the node:fs compat layer in bun.
According to the bun docs, it _should_ work. Apparently it doesn't. Somehow the callback version works, tho, and I don't think there's much of a difference except the verbosity, so let's use it instead. Tested with the example in this repo.
Closes https://github.com/felixmosh/bull-board/issues/949
> fix: use glob callback instead of promise

- packages/nestjs/src/bull-board.root-module.ts
This is an example out of the NestJS documentation: `app.setGlobalPrefix('v1', { exclude: ['cats'] });`
Currently bull-board does not read this setting and the ui becomes non functional if its prefix is in the exclude list.
> Do not apply global prefix if excluded in NestJS config

- packages/ui/localesSync.config.js
- packages/ui/src/constants/languages.ts
- packages/ui/src/services/i18n.ts
- packages/ui/src/static/locales/tr-TR/messages.json
This pull request adds support for Turkish (`tr-TR`) as a secondary language in the application. The changes include updating configuration files, constants, and locale mappings, as well as adding Turkish translations for various UI elements.
> Addition of Turkish Language
